
= Resumen de la unidad 1
Ana Kristell Armenta Sanchez  
Num de control. 17100186


== Descripcion del modelo de caja
Cada vez que se inserta una etiqueta HTML, se crea una caja que encierra el contenido del elemento. + 
Esta caja esta compuesta de 5 partes: content, padding, border, margin y outline, este ultimo siendo de menor importancia ya que no afecta al tamaño del contenedor.

* [ ] *Content:* representa el contenido dentro del modelo de caja, puede ser una imagen, texto, numeros, etc. 

* [ ] *Padding:* es el relleno o espacio libre que existe entre el contenido y el borde. este elemento no es colapsable, no pude tener valores negativos que le ayuden a ocultar un elemento y forma parte del tamaño de la etiqueta HTML.

* [ ] *Border:* Es la linea que encierra completamente el contenido y su relleno.

* [ ] *Margin:* es la separacion entre elementos afuera del border, en esta capa del modelo de cajas se puede presentar el "colapso de margenes" que es cuando un margen es mayor que otro y hace que un elemento este sobrepuesto a otro.

== Display
Es una propiedad que especifica como se visualizaran los elementos dentro del navegador.